<a href="https://colab.research.google.com/github/Komsomolochka/python_netology/blob/master/final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1 Загрузить данные в pandas**

In [0]:
import pandas as pd

In [122]:
data = pd.read_csv('u.data.csv', sep="\t", names = ["user_id", "item_id", "rating", "timestamp"] )
data.head()

   user_id  item_id  rating  timestamp
0      196      242       3  881250949
1      186      302       3  891717742
2       22      377       1  878887116
3      244       51       2  880606923
4      166      346       1  886397596

In [0]:
genre = pd.read_csv('u.genre.csv', sep="|", names = ["genre", "number"] )
genre.head()

        genre  number
0     unknown       0
1      Action       1
2   Adventure       2
3   Animation       3
4  Children's       4

In [0]:
info = pd.read_csv('u.info.csv', sep=" ", names = ["count", "info"] )
info.head()

    count     info
0     943    users
1    1682    items
2  100000  ratings

In [0]:
item = pd.read_csv('u.item.csv', encoding = "ISO-8859-1", sep="|", names = ["movie_id", "movie_title", "release_date", "video_release_date", "IMDb_URL", "unknown", "Action", "Adventure", "Animation", "Children's", "Comedy", "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror", "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western"] )
item.head()

   movie_id        movie_title release_date  ...  Thriller War  Western
0         1   Toy Story (1995)  01-Jan-1995  ...         0   0        0
1         2   GoldenEye (1995)  01-Jan-1995  ...         1   0        0
2         3  Four Rooms (1995)  01-Jan-1995  ...         1   0        0
3         4  Get Shorty (1995)  01-Jan-1995  ...         0   0        0
4         5     Copycat (1995)  01-Jan-1995  ...         1   0        0

[5 rows x 24 columns]

In [0]:
occupation = pd.read_csv('u.occupation.csv', names = ["occupation"] )
occupation.head()

      occupation
0  administrator
1         artist
2         doctor
3       educator
4       engineer

# **2 Посчитайте среднюю оценку, которую поставил каждый пользователь**

In [0]:
rating_by_user = data.groupby(['user_id'])['rating'].mean().reset_index()
rating_by_user.head()

   user_id    rating
0        1  3.610294
1        2  3.709677
2        3  2.796296
3        4  4.333333
4        5  2.874286

# **3 Отсортируйте фильмы по количеству оценок**

In [0]:
movie_by_count = data.groupby(['item_id'])['rating'].count().sort_values(ascending=False).reset_index()
movie_by_count.head()

   item_id  rating
0       50     583
1      258     509
2      100     508
3      181     507
4      294     485

# **4 Средствами pandasa соедините данные по оценкам с данными по пользователям (u.user)**

In [0]:
user = pd.read_csv('u.user.csv', sep="|", names = ["user_id", "age", "gender", "occupation", "zip_code"] )
user.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [0]:
user_and_data = data.merge(user, on='user_id', how='left')
user_and_data.head()

   user_id  item_id  rating  timestamp  age gender  occupation zip_code
0      196      242       3  881250949   49      M      writer    55105
1      186      302       3  891717742   39      F   executive    00000
2       22      377       1  878887116   25      M      writer    40206
3      244       51       2  880606923   28      M  technician    80525
4      166      346       1  886397596   47      M    educator    55113

# **5 Построить модель, которая предсказывает оценку для фильма и пользователя (воспользоваться RandomForestRegressor, тк мы решаем задачу регрессии)**

In [124]:
data = data.drop('timestamp', axis=1)
data.head()

   user_id  item_id  rating
0      196      242       3
1      186      302       3
2       22      377       1
3      244       51       2
4      166      346       1

In [0]:
x = data.drop('rating', axis = 1)
y = data['rating']

In [0]:
import numpy as np
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 50, random_state = 0)

In [135]:
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
                      max_features='auto', max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, n_estimators=50,
                      n_jobs=None, oob_score=False, random_state=0, verbose=0,
                      warm_start=False)

In [0]:
y_pred = regressor.predict(X_test)

# **6 Оценить качество регрессора на отложенной (train_test_split) выборке по одной из метрик на выбор - RMSE, RMAE, R^2**

In [141]:
from sklearn import metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))  
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))  
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.883034
Mean Squared Error: 1.2510267199999998
Root Mean Squared Error: 1.1184930576449725

# **7 Загрузить данные в spark**

In [0]:
!apt-get install openjdk-8-jdk-headless -qq > /dev/null

In [0]:
!wget -q www-us.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz

In [4]:
!tar -xvf spark-2.4.4-bin-hadoop2.7.tgz

spark-2.4.4-bin-hadoop2.7/
spark-2.4.4-bin-hadoop2.7/R/
spark-2.4.4-bin-hadoop2.7/R/lib/
spark-2.4.4-bin-hadoop2.7/R/lib/sparkr.zip
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/INDEX
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/html/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/html/R.css
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/html/00Index.html
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/help/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/help/aliases.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/help/AnIndex
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdx
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/help/SparkR.rdb
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/help/paths.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/worker/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/worker/worker.R
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/worker/daemon.R
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/tests/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/tests/testthat/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/tests/testthat/test_basic.R
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/profile/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/profile/shell.R
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/profile/general.R
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/R/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdx
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/R/SparkR.rdb
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/R/SparkR
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/Meta/
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/Meta/nsInfo.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/Meta/links.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/Meta/hsearch.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/Meta/Rd.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/Meta/features.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/Meta/package.rds
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/DESCRIPTION
spark-2.4.4-bin-hadoop2.7/R/lib/SparkR/NAMESPACE
spark-2.4.4-bin-hadoop2.7/sbin/
spark-2.4.4-bin-hadoop2.7/sbin/stop-shuffle-service.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-thriftserver.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-slave.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-shuffle-service.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-mesos-shuffle-service.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-master.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-history-server.sh
spark-2.4.4-bin-hadoop2.7/sbin/spark-config.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-thriftserver.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-slaves.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-slave.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-mesos-shuffle-service.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-mesos-dispatcher.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-master.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-history-server.sh
spark-2.4.4-bin-hadoop2.7/sbin/stop-all.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-slaves.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-mesos-dispatcher.sh
spark-2.4.4-bin-hadoop2.7/sbin/start-all.sh
spark-2.4.4-bin-hadoop2.7/sbin/spark-daemons.sh
spark-2.4.4-bin-hadoop2.7/sbin/spark-daemon.sh
spark-2.4.4-bin-hadoop2.7/sbin/slaves.sh
spark-2.4.4-bin-hadoop2.7/python/
spark-2.4.4-bin-hadoop2.7/python/dist/
spark-2.4.4-bin-hadoop2.7/python/pyspark.egg-info/
spark-2.4.4-bin-hadoop2.7/python/pyspark.egg-info/SOURCES.txt
spark-2.4.4-bin-hadoop2.7/python/pyspark.egg-info/dependency_links.txt
spark-2.4.4-bin-hadoop2.7/python/pyspark.egg-info/top_level.txt
spark-2.4.4-bin-hadoop2.7/python/pyspark.egg-info/PKG-INFO
spark-2.4.4-bin-hadoop2.7/python/pyspark.egg-info/requires.txt
spark-2.4.4-bin-hadoop2.7/python/README.md
spark-2.4.4-bin-hadoop2.7/python/MANIFEST.in
spark-2.4.4-bin-hadoop2.7/python/setup.py
spark-2.4.4-bin-hadoop2.7/python/run-tests.py
spark-2.4.4-bin-hadoop2.7/python/run-tests-with-coverage
spark-2.4.4-bin-hadoop2.7/python/test_support/
spark-2.4.4-bin-hadoop2.7/python/test_support/userlibrary.py
spark-2.4.4-bin-hadoop2.7/python/test_support/userlib-0.1.zip
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/text-test.txt
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/streaming/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/streaming/text-test.txt
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/people_array_utf16le.json
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/people_array.json
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/people1.json
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/people.json
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=9/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=9/day=1/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=9/day=1/part-r-00007.gz.parquet
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=9/day=1/.part-r-00007.gz.parquet.crc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=26/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=26/part-r-00005.gz.parquet
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=26/.part-r-00005.gz.parquet.crc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=25/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=25/part-r-00004.gz.parquet
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=25/part-r-00002.gz.parquet
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=25/.part-r-00004.gz.parquet.crc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2015/month=10/day=25/.part-r-00002.gz.parquet.crc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2014/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2014/month=9/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2014/month=9/day=1/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2014/month=9/day=1/part-r-00008.gz.parquet
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/year=2014/month=9/day=1/.part-r-00008.gz.parquet.crc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/_metadata
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/_common_metadata
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/parquet_partitioned/_SUCCESS
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=1/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=1/c=1/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=1/c=1/part-r-00000-829af031-b970-49d6-ad39-30460a0be2c8.orc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=1/c=1/.part-r-00000-829af031-b970-49d6-ad39-30460a0be2c8.orc.crc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=0/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=0/c=0/
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=0/c=0/part-r-00000-829af031-b970-49d6-ad39-30460a0be2c8.orc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/b=0/c=0/.part-r-00000-829af031-b970-49d6-ad39-30460a0be2c8.orc.crc
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/orc_partitioned/_SUCCESS
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/ages_newlines.csv
spark-2.4.4-bin-hadoop2.7/python/test_support/sql/ages.csv
spark-2.4.4-bin-hadoop2.7/python/test_support/hello/
spark-2.4.4-bin-hadoop2.7/python/test_support/hello/sub_hello/
spark-2.4.4-bin-hadoop2.7/python/test_support/hello/sub_hello/sub_hello.txt
spark-2.4.4-bin-hadoop2.7/python/test_support/hello/hello.txt
spark-2.4.4-bin-hadoop2.7/python/test_support/SimpleHTTPServer.py
spark-2.4.4-bin-hadoop2.7/python/test_coverage/
spark-2.4.4-bin-hadoop2.7/python/test_coverage/sitecustomize.py
spark-2.4.4-bin-hadoop2.7/python/test_coverage/coverage_daemon.py
spark-2.4.4-bin-hadoop2.7/python/test_coverage/conf/
spark-2.4.4-bin-hadoop2.7/python/test_coverage/conf/spark-defaults.conf
spark-2.4.4-bin-hadoop2.7/python/setup.cfg
spark-2.4.4-bin-hadoop2.7/python/run-tests
spark-2.4.4-bin-hadoop2.7/python/pyspark/
spark-2.4.4-bin-hadoop2.7/python/pyspark/python/
spark-2.4.4-bin-hadoop2.7/python/pyspark/python/pyspark/
spark-2.4.4-bin-hadoop2.7/python/pyspark/python/pyspark/shell.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/shuffle.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/serializers.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/rdd.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/profiler.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/java_gateway.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/files.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/daemon.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/context.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/conf.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/cloudpickle.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/broadcast.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/accumulators.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/worker.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/version.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/util.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/tests.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/test_serializers.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/test_broadcast.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/taskcontext.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/storagelevel.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/traceback_utils.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/tests.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/kinesis.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/kafka.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/flume.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/dstream.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/context.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/util.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/listener.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/streaming/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/status.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/statcounter.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/tests.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/streaming.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/session.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/readwriter.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/functions.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/dataframe.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/context.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/window.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/utils.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/udf.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/types.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/group.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/conf.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/column.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/catalog.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/sql/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/shell.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/resultiterable.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/rddsampler.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/util.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/tree.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/tests.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/regression.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/recommendation.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/random.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/fpm.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/feature.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/evaluation.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/clustering.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/classification.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/stat/
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/stat/_statistics.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/stat/test.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/stat/distribution.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/stat/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/stat/KernelDensity.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/linalg/
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/linalg/distributed.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/linalg/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/common.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/mllib/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/wrapper.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/util.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/tuning.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/tests.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/regression.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/recommendation.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/image.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/fpm.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/feature.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/evaluation.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/clustering.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/classification.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/stat.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/pipeline.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/param/
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/param/shared.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/param/_shared_params_code_gen.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/param/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/linalg/
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/linalg/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/common.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/base.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/ml/__init__.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/join.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/heapq3.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/find_spark_home.py
spark-2.4.4-bin-hadoop2.7/python/pyspark/_globals.py
spark-2.4.4-bin-hadoop2.7/python/pylintrc
spark-2.4.4-bin-hadoop2.7/python/lib/
spark-2.4.4-bin-hadoop2.7/python/lib/pyspark.zip
spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip
spark-2.4.4-bin-hadoop2.7/python/lib/PY4J_LICENSE.txt
spark-2.4.4-bin-hadoop2.7/python/docs/
spark-2.4.4-bin-hadoop2.7/python/docs/pyspark.streaming.rst
spark-2.4.4-bin-hadoop2.7/python/docs/pyspark.sql.rst
spark-2.4.4-bin-hadoop2.7/python/docs/epytext.py
spark-2.4.4-bin-hadoop2.7/python/docs/conf.py
spark-2.4.4-bin-hadoop2.7/python/docs/Makefile
spark-2.4.4-bin-hadoop2.7/python/docs/pyspark.rst
spark-2.4.4-bin-hadoop2.7/python/docs/pyspark.mllib.rst
spark-2.4.4-bin-hadoop2.7/python/docs/pyspark.ml.rst
spark-2.4.4-bin-hadoop2.7/python/docs/make2.bat
spark-2.4.4-bin-hadoop2.7/python/docs/make.bat
spark-2.4.4-bin-hadoop2.7/python/docs/index.rst
spark-2.4.4-bin-hadoop2.7/python/docs/_templates/
spark-2.4.4-bin-hadoop2.7/python/docs/_templates/layout.html
spark-2.4.4-bin-hadoop2.7/python/docs/_static/
spark-2.4.4-bin-hadoop2.7/python/docs/_static/pyspark.js
spark-2.4.4-bin-hadoop2.7/python/docs/_static/pyspark.css
spark-2.4.4-bin-hadoop2.7/python/.gitignore
spark-2.4.4-bin-hadoop2.7/python/.coveragerc
spark-2.4.4-bin-hadoop2.7/bin/
spark-2.4.4-bin-hadoop2.7/bin/spark-class
spark-2.4.4-bin-hadoop2.7/bin/pyspark2.cmd
spark-2.4.4-bin-hadoop2.7/bin/pyspark
spark-2.4.4-bin-hadoop2.7/bin/load-spark-env.sh
spark-2.4.4-bin-hadoop2.7/bin/load-spark-env.cmd
spark-2.4.4-bin-hadoop2.7/bin/docker-image-tool.sh
spark-2.4.4-bin-hadoop2.7/bin/sparkR2.cmd
spark-2.4.4-bin-hadoop2.7/bin/sparkR.cmd
spark-2.4.4-bin-hadoop2.7/bin/sparkR
spark-2.4.4-bin-hadoop2.7/bin/spark-submit2.cmd
spark-2.4.4-bin-hadoop2.7/bin/spark-submit.cmd
spark-2.4.4-bin-hadoop2.7/bin/spark-submit
spark-2.4.4-bin-hadoop2.7/bin/spark-sql2.cmd
spark-2.4.4-bin-hadoop2.7/bin/spark-sql.cmd
spark-2.4.4-bin-hadoop2.7/bin/spark-sql
spark-2.4.4-bin-hadoop2.7/bin/spark-shell2.cmd
spark-2.4.4-bin-hadoop2.7/bin/spark-shell.cmd
spark-2.4.4-bin-hadoop2.7/bin/spark-shell
spark-2.4.4-bin-hadoop2.7/bin/spark-class2.cmd
spark-2.4.4-bin-hadoop2.7/bin/spark-class.cmd
spark-2.4.4-bin-hadoop2.7/bin/run-example.cmd
spark-2.4.4-bin-hadoop2.7/bin/run-example
spark-2.4.4-bin-hadoop2.7/bin/pyspark.cmd
spark-2.4.4-bin-hadoop2.7/bin/find-spark-home.cmd
spark-2.4.4-bin-hadoop2.7/bin/find-spark-home
spark-2.4.4-bin-hadoop2.7/bin/beeline.cmd
spark-2.4.4-bin-hadoop2.7/bin/beeline
spark-2.4.4-bin-hadoop2.7/README.md
spark-2.4.4-bin-hadoop2.7/conf/
spark-2.4.4-bin-hadoop2.7/conf/spark-env.sh.template
spark-2.4.4-bin-hadoop2.7/conf/spark-defaults.conf.template
spark-2.4.4-bin-hadoop2.7/conf/slaves.template
spark-2.4.4-bin-hadoop2.7/conf/metrics.properties.template
spark-2.4.4-bin-hadoop2.7/conf/log4j.properties.template
spark-2.4.4-bin-hadoop2.7/conf/fairscheduler.xml.template
spark-2.4.4-bin-hadoop2.7/conf/docker.properties.template
spark-2.4.4-bin-hadoop2.7/data/
spark-2.4.4-bin-hadoop2.7/data/mllib/
spark-2.4.4-bin-hadoop2.7/data/mllib/gmm_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/als/
spark-2.4.4-bin-hadoop2.7/data/mllib/als/test.data
spark-2.4.4-bin-hadoop2.7/data/mllib/als/sample_movielens_ratings.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/streaming_kmeans_data_test.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_svm_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_multiclass_classification_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_movielens_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_linear_regression_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_libsvm_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_lda_libsvm_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_lda_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_kmeans_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_isotonic_regression_libsvm_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_fpgrowth.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/sample_binary_classification_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/ridge-data/
spark-2.4.4-bin-hadoop2.7/data/mllib/ridge-data/lpsa.data
spark-2.4.4-bin-hadoop2.7/data/mllib/pic_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/pagerank_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/kmeans_data.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/iris_libsvm.txt
spark-2.4.4-bin-hadoop2.7/data/mllib/images/
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/grayscale.jpg
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-02/chr30.4.184.jpg
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA_alpha_60.png
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=multichannel/date=2018-01/BGRA.png
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP802813.jpg
spark-2.4.4-bin-hadoop2.7/data/mllib/images/partitioned/cls=kittens/date=2018-02/DP153539.jpg

In [0]:
!pip install -q findspark

In [0]:
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-2.4.4-bin-hadoop2.7"

In [0]:
import findspark
findspark.init()
from pyspark.sql import SparkSession

spark = SparkSession.builder.master("local[*]").getOrCreate()

In [0]:
from pyspark.sql.types import StructType, StructField, IntegerType, StringType, DateType, DoubleType

In [0]:
schema1 = StructType([StructField("user_id", IntegerType()),StructField("item_id", IntegerType()),StructField("rating", IntegerType()),StructField("timestamp", IntegerType())])

In [11]:
data = spark.read.csv('u.data.csv', sep="\t", header=False, schema=schema1)
data.show()

+-------+-------+------+---------+
|user_id|item_id|rating|timestamp|
+-------+-------+------+---------+
|    196|    242|     3|881250949|
|    186|    302|     3|891717742|
|     22|    377|     1|878887116|
|    244|     51|     2|880606923|
|    166|    346|     1|886397596|
|    298|    474|     4|884182806|
|    115|    265|     2|881171488|
|    253|    465|     5|891628467|
|    305|    451|     3|886324817|
|      6|     86|     3|883603013|
|     62|    257|     2|879372434|
|    286|   1014|     5|879781125|
|    200|    222|     5|876042340|
|    210|     40|     3|891035994|
|    224|     29|     3|888104457|
|    303|    785|     3|879485318|
|    122|    387|     5|879270459|
|    194|    274|     2|879539794|
|    291|   1042|     4|874834944|
|    234|   1184|     2|892079237|
+-------+-------+------+---------+
only showing top 20 rows

In [0]:
schema2 = StructType([StructField("genre", StringType()),StructField("genre_id", IntegerType())])

In [13]:
genre = spark.read.csv('u.genre.csv', sep="|", header=False, schema=schema2)
genre.show()

+-----------+--------+
|      genre|genre_id|
+-----------+--------+
|    unknown|       0|
|     Action|       1|
|  Adventure|       2|
|  Animation|       3|
| Children's|       4|
|     Comedy|       5|
|      Crime|       6|
|Documentary|       7|
|      Drama|       8|
|    Fantasy|       9|
|  Film-Noir|      10|
|     Horror|      11|
|    Musical|      12|
|    Mystery|      13|
|    Romance|      14|
|     Sci-Fi|      15|
|   Thriller|      16|
|        War|      17|
|    Western|      18|
+-----------+--------+

In [0]:
schema4 = StructType([StructField("movie_id", IntegerType()), StructField("movie_title", StringType()), StructField("release_date", StringType()), StructField("video_release_date", StringType()), StructField("IMDb_URL", StringType()), StructField("unknown", IntegerType()),StructField( "Action", IntegerType()), StructField("Adventure", IntegerType()), StructField("Animation", IntegerType()), StructField("Children's", IntegerType()), StructField("Comedy", IntegerType()), StructField("Crime", IntegerType()), StructField("Documentary", IntegerType()), StructField("Drama", IntegerType()), StructField("Fantasy", IntegerType()), StructField("Film-Noir", IntegerType()), StructField("Horror", IntegerType()), StructField("Musical", IntegerType()), StructField("Mystery", IntegerType()), StructField("Romance", IntegerType()), StructField("Sci-Fi", IntegerType()), StructField("Thriller", IntegerType()), StructField("War", IntegerType()), StructField("Western", IntegerType())])

In [68]:
item = spark.read.csv('u.item.csv', sep="|", header=False, schema=schema4)
item.show()

+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|Animation|Children's|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|       1|    Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        1|         1|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       2|    GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        1|        0|         0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       3|   Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       4|   Get Shorty (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     1|        0|        0|         0|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       5|      Copycat (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    1|          0|    1|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|       6|Shanghai Triad (Y...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       7|Twelve Monkeys (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     1|       0|  0|      0|
|       8|         Babe (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         1|     1|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       9|Dead Man Walking ...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      10|  Richard III (1995)| 22-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  1|      0|
|      11|Seven (Se7en) (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|      12|Usual Suspects, T...| 14-Aug-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    1|          0|    0|      0|        0|     0|      0|      0|      0|     0|       1|  0|      0|
|      13|Mighty Aphrodite ...| 30-Oct-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      14|  Postino, Il (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
|      15|Mr. Holland's Opu...| 29-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      16|French Twist (Gaz...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     1|    0|          0|    0|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
|      17|From Dusk Till Da...| 05-Feb-1996|              null|http://us.imdb.co...|      0|     1|        0|        0|         0|     1|    1|          0|    0|      0|        0|     1|      0|      0|      0|     0|       1|  0|      0|
|      18|White Balloon, Th...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      19|Antonia's Line (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      20|Angels and Insect...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    1|      0|        0|     0|      0|      0|      1|     0|       0|  0|      0|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 20 rows

# **8 Средствами спарка вывести среднюю оценку для каждого фильма**

In [0]:
item_by_rating = data.groupBy('item_id').mean('rating')
item_by_rating.show()

+-------+------------------+
|item_id|       avg(rating)|
+-------+------------------+
|    496| 4.121212121212121|
|    471|3.6108597285067874|
|    463| 3.859154929577465|
|    148|          3.203125|
|   1342|               2.5|
|    833| 3.204081632653061|
|   1088| 2.230769230769231|
|   1591|3.1666666666666665|
|   1238|             3.125|
|   1580|               1.0|
|   1645|               4.0|
|    392|3.5441176470588234|
|    623| 2.923076923076923|
|    540| 2.511627906976744|
|    858|               1.0|
|    737| 2.983050847457627|
|    243|2.4393939393939394|
|   1025|2.9318181818181817|
|   1084| 3.857142857142857|
|   1127| 2.909090909090909|
+-------+------------------+
only showing top 20 rows

# **9 В спарке получить 2 датафрейма с 5-ю самыми популярными и самыми непопулярными фильмами (по количеству оценок, либо по самой оценке - на Ваш выбор)**

In [0]:
from pyspark.sql.functions import col
df_max_rating = item_by_rating.sort(col('avg(rating)').desc()).limit(5)
df_max_rating.show()

+-------+-----------+
|item_id|avg(rating)|
+-------+-----------+
|   1500|        5.0|
|   1653|        5.0|
|   1201|        5.0|
|   1122|        5.0|
|   1599|        5.0|
+-------+-----------+

In [0]:
from pyspark.sql.functions import col
df_min_rating = item_by_rating.sort(col('avg(rating)').asc()).limit(5)
df_min_rating.take(5)
df_min_rating.show()

+-------+-----------+
|item_id|avg(rating)|
+-------+-----------+
|   1339|        1.0|
|    858|        1.0|
|   1618|        1.0|
|   1580|        1.0|
|   1352|        1.0|
+-------+-----------+

# ** 10 Средствами спарка соедините информацию по фильмам и жанрам (u.genre) Дублирование строк в данном случае - ок.Интересует такая структура - id фильма | название фильма | жанр**

In [0]:
all_column_names = item.columns

In [0]:
columns_to_remove = ['movie_id',
 'movie_title',
 'release_date',
 'video_release_date',
 'IMDb_URL']

In [71]:
columns_for_replacement = [i for i in all_column_names if i not in columns_to_remove]
columns_for_replacement

['unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [72]:
from pyspark.sql.functions import col, when
for i in columns_for_replacement:
    item = item.withColumn(i,when((col(i)==1), i).otherwise(col(i)))
item.show()

+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|Animation|Children's|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller|War|Western|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
|       1|    Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|Animation|Children's|Comedy|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       2|    GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|Action|Adventure|        0|         0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|Thriller|  0|      0|
|       3|   Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|Thriller|  0|      0|
|       4|   Get Shorty (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|Action|        0|        0|         0|Comedy|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       5|      Copycat (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|Crime|          0|Drama|      0|        0|     0|      0|      0|      0|     0|Thriller|  0|      0|
|       6|Shanghai Triad (Y...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       7|Twelve Monkeys (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|      0|Sci-Fi|       0|  0|      0|
|       8|         Babe (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|Children's|Comedy|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|       9|Dead Man Walking ...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      10|  Richard III (1995)| 22-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|War|      0|
|      11|Seven (Se7en) (1995)| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|Crime|          0|    0|      0|        0|     0|      0|      0|      0|     0|Thriller|  0|      0|
|      12|Usual Suspects, T...| 14-Aug-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|Crime|          0|    0|      0|        0|     0|      0|      0|      0|     0|Thriller|  0|      0|
|      13|Mighty Aphrodite ...| 30-Oct-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|Comedy|    0|          0|    0|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      14|  Postino, Il (1994)| 01-Jan-1994|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|Romance|     0|       0|  0|      0|
|      15|Mr. Holland's Opu...| 29-Jan-1996|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      16|French Twist (Gaz...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|Comedy|    0|          0|    0|      0|        0|     0|      0|      0|Romance|     0|       0|  0|      0|
|      17|From Dusk Till Da...| 05-Feb-1996|              null|http://us.imdb.co...|      0|Action|        0|        0|         0|Comedy|Crime|          0|    0|      0|        0|Horror|      0|      0|      0|     0|Thriller|  0|      0|
|      18|White Balloon, Th...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      19|Antonia's Line (1...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|      0|     0|       0|  0|      0|
|      20|Angels and Insect...| 01-Jan-1995|              null|http://us.imdb.co...|      0|     0|        0|        0|         0|     0|    0|          0|Drama|      0|        0|     0|      0|      0|Romance|     0|       0|  0|      0|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+---+-------+
only showing top 20 rows

In [73]:
from pyspark.sql.functions import col, when
for i in columns_for_replacement:
    item = item.withColumn(i,when((col(i)==0), None).otherwise(col(i)))
item.show()

+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+
|movie_id|         movie_title|release_date|video_release_date|            IMDb_URL|unknown|Action|Adventure|Animation|Children's|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller| War|Western|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+
|       1|    Toy Story (1995)| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|Animation|Children's|Comedy| null|       null| null|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       2|    GoldenEye (1995)| 01-Jan-1995|              null|http://us.imdb.co...|   null|Action|Adventure|     null|      null|  null| null|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|       3|   Four Rooms (1995)| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|       4|   Get Shorty (1995)| 01-Jan-1995|              null|http://us.imdb.co...|   null|Action|     null|     null|      null|Comedy| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       5|      Copycat (1995)| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null|Crime|       null|Drama|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|       6|Shanghai Triad (Y...| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       7|Twelve Monkeys (1...| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|Sci-Fi|    null|null|   null|
|       8|         Babe (1995)| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|Children's|Comedy| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       9|Dead Man Walking ...| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      10|  Richard III (1995)| 22-Jan-1996|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null| War|   null|
|      11|Seven (Se7en) (1995)| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null|Crime|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|      12|Usual Suspects, T...| 14-Aug-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null|Crime|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|      13|Mighty Aphrodite ...| 30-Oct-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|Comedy| null|       null| null|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      14|  Postino, Il (1994)| 01-Jan-1994|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|
|      15|Mr. Holland's Opu...| 29-Jan-1996|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      16|French Twist (Gaz...| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|Comedy| null|       null| null|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|
|      17|From Dusk Till Da...| 05-Feb-1996|              null|http://us.imdb.co...|   null|Action|     null|     null|      null|Comedy|Crime|       null| null|   null|     null|Horror|   null|   null|   null|  null|Thriller|null|   null|
|      18|White Balloon, Th...| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      19|Antonia's Line (1...| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      20|Angels and Insect...| 01-Jan-1995|              null|http://us.imdb.co...|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|
+--------+--------------------+------------+------------------+--------------------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+
only showing top 20 rows

In [84]:
item1 = item.drop('release_date', 'video_release_date', 'IMDb_URL', 'movie_title')
item1.show()

+--------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+
|movie_id|unknown|Action|Adventure|Animation|Children's|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller| War|Western|
+--------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+
|       1|   null|  null|     null|Animation|Children's|Comedy| null|       null| null|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       2|   null|Action|Adventure|     null|      null|  null| null|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|       3|   null|  null|     null|     null|      null|  null| null|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|       4|   null|Action|     null|     null|      null|Comedy| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       5|   null|  null|     null|     null|      null|  null|Crime|       null|Drama|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|       6|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       7|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|Sci-Fi|    null|null|   null|
|       8|   null|  null|     null|     null|Children's|Comedy| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|       9|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      10|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null| War|   null|
|      11|   null|  null|     null|     null|      null|  null|Crime|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|      12|   null|  null|     null|     null|      null|  null|Crime|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|
|      13|   null|  null|     null|     null|      null|Comedy| null|       null| null|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      14|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|
|      15|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      16|   null|  null|     null|     null|      null|Comedy| null|       null| null|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|
|      17|   null|Action|     null|     null|      null|Comedy|Crime|       null| null|   null|     null|Horror|   null|   null|   null|  null|Thriller|null|   null|
|      18|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      19|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|
|      20|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|
+--------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+
only showing top 20 rows

In [0]:
import pyspark.sql.functions as f
item1 = item1.withColumn('genre', f.concat_ws(',', *[c for c in item1.columns if c!='movie_id']))

In [86]:
item1.show()

+--------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+--------------------+
|movie_id|unknown|Action|Adventure|Animation|Children's|Comedy|Crime|Documentary|Drama|Fantasy|Film-Noir|Horror|Musical|Mystery|Romance|Sci-Fi|Thriller| War|Western|               genre|
+--------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+--------------------+
|       1|   null|  null|     null|Animation|Children's|Comedy| null|       null| null|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|Animation,Childre...|
|       2|   null|Action|Adventure|     null|      null|  null| null|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|Action,Adventure,...|
|       3|   null|  null|     null|     null|      null|  null| null|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|            Thriller|
|       4|   null|Action|     null|     null|      null|Comedy| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null| Action,Comedy,Drama|
|       5|   null|  null|     null|     null|      null|  null|Crime|       null|Drama|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|Crime,Drama,Thriller|
|       6|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|               Drama|
|       7|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|Sci-Fi|    null|null|   null|        Drama,Sci-Fi|
|       8|   null|  null|     null|     null|Children's|Comedy| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|Children's,Comedy...|
|       9|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|               Drama|
|      10|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null| War|   null|           Drama,War|
|      11|   null|  null|     null|     null|      null|  null|Crime|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|      Crime,Thriller|
|      12|   null|  null|     null|     null|      null|  null|Crime|       null| null|   null|     null|  null|   null|   null|   null|  null|Thriller|null|   null|      Crime,Thriller|
|      13|   null|  null|     null|     null|      null|Comedy| null|       null| null|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|              Comedy|
|      14|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|       Drama,Romance|
|      15|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|               Drama|
|      16|   null|  null|     null|     null|      null|Comedy| null|       null| null|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|      Comedy,Romance|
|      17|   null|Action|     null|     null|      null|Comedy|Crime|       null| null|   null|     null|Horror|   null|   null|   null|  null|Thriller|null|   null|Action,Comedy,Cri...|
|      18|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|               Drama|
|      19|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|   null|  null|    null|null|   null|               Drama|
|      20|   null|  null|     null|     null|      null|  null| null|       null|Drama|   null|     null|  null|   null|   null|Romance|  null|    null|null|   null|       Drama,Romance|
+--------+-------+------+---------+---------+----------+------+-----+-----------+-----+-------+---------+------+-------+-------+-------+------+--------+----+-------+--------------------+
only showing top 20 rows

In [79]:
item3 = item.select('movie_id', 'movie_title')
item3.show()

+--------+--------------------+
|movie_id|         movie_title|
+--------+--------------------+
|       1|    Toy Story (1995)|
|       2|    GoldenEye (1995)|
|       3|   Four Rooms (1995)|
|       4|   Get Shorty (1995)|
|       5|      Copycat (1995)|
|       6|Shanghai Triad (Y...|
|       7|Twelve Monkeys (1...|
|       8|         Babe (1995)|
|       9|Dead Man Walking ...|
|      10|  Richard III (1995)|
|      11|Seven (Se7en) (1995)|
|      12|Usual Suspects, T...|
|      13|Mighty Aphrodite ...|
|      14|  Postino, Il (1994)|
|      15|Mr. Holland's Opu...|
|      16|French Twist (Gaz...|
|      17|From Dusk Till Da...|
|      18|White Balloon, Th...|
|      19|Antonia's Line (1...|
|      20|Angels and Insect...|
+--------+--------------------+
only showing top 20 rows

In [87]:
item4 = item1.select('movie_id', 'genre')
item4.show()

+--------+--------------------+
|movie_id|               genre|
+--------+--------------------+
|       1|Animation,Childre...|
|       2|Action,Adventure,...|
|       3|            Thriller|
|       4| Action,Comedy,Drama|
|       5|Crime,Drama,Thriller|
|       6|               Drama|
|       7|        Drama,Sci-Fi|
|       8|Children's,Comedy...|
|       9|               Drama|
|      10|           Drama,War|
|      11|      Crime,Thriller|
|      12|      Crime,Thriller|
|      13|              Comedy|
|      14|       Drama,Romance|
|      15|               Drama|
|      16|      Comedy,Romance|
|      17|Action,Comedy,Cri...|
|      18|               Drama|
|      19|               Drama|
|      20|       Drama,Romance|
+--------+--------------------+
only showing top 20 rows

In [104]:
films_and_genre_join = item3.join(item4, on='movie_id', how='left')
films_and_genre_join.show()

+--------+--------------------+--------------------+
|movie_id|         movie_title|               genre|
+--------+--------------------+--------------------+
|       1|    Toy Story (1995)|Animation,Childre...|
|       2|    GoldenEye (1995)|Action,Adventure,...|
|       3|   Four Rooms (1995)|            Thriller|
|       4|   Get Shorty (1995)| Action,Comedy,Drama|
|       5|      Copycat (1995)|Crime,Drama,Thriller|
|       6|Shanghai Triad (Y...|               Drama|
|       7|Twelve Monkeys (1...|        Drama,Sci-Fi|
|       8|         Babe (1995)|Children's,Comedy...|
|       9|Dead Man Walking ...|               Drama|
|      10|  Richard III (1995)|           Drama,War|
|      11|Seven (Se7en) (1995)|      Crime,Thriller|
|      12|Usual Suspects, T...|      Crime,Thriller|
|      13|Mighty Aphrodite ...|              Comedy|
|      14|  Postino, Il (1994)|       Drama,Romance|
|      15|Mr. Holland's Opu...|               Drama|
|      16|French Twist (Gaz...|      Comedy,Romance|
|      17|From Dusk Till Da...|Action,Comedy,Cri...|
|      18|White Balloon, Th...|               Drama|
|      19|Antonia's Line (1...|               Drama|
|      20|Angels and Insect...|       Drama,Romance|
+--------+--------------------+--------------------+
only showing top 20 rows

In [108]:
from pyspark.sql.functions import col, explode, regexp_replace, split

films = films_and_genre_join.withColumn(
    "genre", 
    explode(split(col("genre"), ","))
)
films.show()

+--------+--------------------+----------+
|movie_id|         movie_title|     genre|
+--------+--------------------+----------+
|       1|    Toy Story (1995)| Animation|
|       1|    Toy Story (1995)|Children's|
|       1|    Toy Story (1995)|    Comedy|
|       2|    GoldenEye (1995)|    Action|
|       2|    GoldenEye (1995)| Adventure|
|       2|    GoldenEye (1995)|  Thriller|
|       3|   Four Rooms (1995)|  Thriller|
|       4|   Get Shorty (1995)|    Action|
|       4|   Get Shorty (1995)|    Comedy|
|       4|   Get Shorty (1995)|     Drama|
|       5|      Copycat (1995)|     Crime|
|       5|      Copycat (1995)|     Drama|
|       5|      Copycat (1995)|  Thriller|
|       6|Shanghai Triad (Y...|     Drama|
|       7|Twelve Monkeys (1...|     Drama|
|       7|Twelve Monkeys (1...|    Sci-Fi|
|       8|         Babe (1995)|Children's|
|       8|         Babe (1995)|    Comedy|
|       8|         Babe (1995)|     Drama|
|       9|Dead Man Walking ...|     Drama|
+--------+--------------------+----------+
only showing top 20 rows

# ** 11 Посчитайте средствами спарка среднюю оценку для каждого жанра**

In [116]:
data_and_films = data.join(films, data.item_id==films.movie_id)
data_and_films.show()

+-------+-------+------+---------+--------+----------------+---------+
|user_id|item_id|rating|timestamp|movie_id|     movie_title|    genre|
+-------+-------+------+---------+--------+----------------+---------+
|    637|      1|     4|882902924|       1|Toy Story (1995)|Animation|
|    777|      1|     4|875979431|       1|Toy Story (1995)|Animation|
|    798|      1|     4|875295695|       1|Toy Story (1995)|Animation|
|    614|      1|     5|879464093|       1|Toy Story (1995)|Animation|
|    697|      1|     5|882622481|       1|Toy Story (1995)|Animation|
|    253|      1|     5|891628467|       1|Toy Story (1995)|Animation|
|    677|      1|     4|889399229|       1|Toy Story (1995)|Animation|
|    178|      1|     4|882823805|       1|Toy Story (1995)|Animation|
|    562|      1|     2|879194894|       1|Toy Story (1995)|Animation|
|    643|      1|     5|891445287|       1|Toy Story (1995)|Animation|
|    676|      1|     5|892686188|       1|Toy Story (1995)|Animation|
|    588|      1|     4|890015684|       1|Toy Story (1995)|Animation|
|    613|      1|     4|891227410|       1|Toy Story (1995)|Animation|
|    465|      1|     4|883530054|       1|Toy Story (1995)|Animation|
|    763|      1|     4|878915559|       1|Toy Story (1995)|Animation|
|    716|      1|     5|879793192|       1|Toy Story (1995)|Animation|
|    467|      1|     4|879532459|       1|Toy Story (1995)|Animation|
|     92|      1|     4|875810511|       1|Toy Story (1995)|Animation|
|    381|      1|     5|892697394|       1|Toy Story (1995)|Animation|
|    478|      1|     4|889387931|       1|Toy Story (1995)|Animation|
+-------+-------+------+---------+--------+----------------+---------+
only showing top 20 rows

In [117]:
rating_by_genre = data_and_films.groupBy('genre').mean('rating')
rating_by_genre.show()

+-----------+------------------+
|      genre|       avg(rating)|
+-----------+------------------+
|      Crime|3.6480917817841254|
|    Romance|3.6236893203883493|
|   Thriller|3.5082037625633538|
|  Adventure|3.5026935072299406|
|    unknown|             3.375|
| Children's|3.3459387483355525|
|      Drama|3.6965183479772588|
|        War|  3.81631395109924|
|Documentary|3.6733780760626398|
|    Fantasy|3.2531468531468533|
|    Mystery| 3.636100036245016|
|    Musical|3.5629544584768467|
|  Animation| 3.570203644158628|
|  Film-Noir|3.9226519337016574|
|     Horror|3.3182922596320723|
|    Western| 3.637810945273632|
|     Comedy| 3.398479708506094|
|     Action|3.4808126410835216|
|     Sci-Fi|3.5710850616170724|
+-----------+------------------+